[workspace]
resolver = "3"
members = [
    "libs/disco-foundation",
    "libs/disco-leader",
    "libs/disco-macros",
    "libs/disco-tester",
    "libs/disco-worker",
    "examples/multiplicator/multiplicator-foundation",
    "examples/multiplicator/multiplicator-leader",
    "examples/multiplicator/multiplicator-worker",
    "examples/multiplicator/multiplicator-tester",
]