use std::collections::BTreeSet;
use std::fmt;

use serde::{Deserialize, Serialize};

use crate::clock::Timestamp;
use crate::device::DeviceId;

/// A capability advertised by a device (CPU, GPU, storage, custom hardware, ...).
///
/// Implementors are usually zero-sized marker types generated by the
/// [`crate::capability!`] macro; only the stable [`Capability::NAME`] is used for
/// matching, so capabilities can be compared across nodes without sharing types.
pub trait Capability: Send + Sync + 'static {
    const NAME: &'static str;
    const VERSION: u32 = 1;
}

/// Stable, string-backed identifier for a capability.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct CapabilityId(pub String);

impl CapabilityId {
    pub fn new(name: impl Into<String>) -> Self {
        CapabilityId(name.into())
    }
}

impl<T: Capability> From<T> for CapabilityId {
    fn from(_: T) -> Self {
        CapabilityId(T::NAME.to_string())
    }
}

impl From<&str> for CapabilityId {
    fn from(value: &str) -> Self {
        CapabilityId(value.to_string())
    }
}

impl fmt::Display for CapabilityId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// An order-independent collection of capabilities attached to a device.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct CapabilitySet {
    inner: BTreeSet<CapabilityId>,
}

impl CapabilitySet {
    pub const fn new() -> Self {
        CapabilitySet {
            inner: BTreeSet::new(),
        }
    }

    pub fn insert<T: Capability>(&mut self, _capability: T) -> bool {
        self.inner.insert(CapabilityId::new(T::NAME))
    }

    pub fn insert_id(&mut self, id: impl Into<CapabilityId>) -> bool {
        self.inner.insert(id.into())
    }

    pub fn remove<T: Capability>(&mut self) -> bool {
        self.inner.remove(&CapabilityId::new(T::NAME))
    }

    pub fn contains<T: Capability>(&self) -> bool {
        self.inner.contains(&CapabilityId::new(T::NAME))
    }

    pub fn contains_id(&self, id: &CapabilityId) -> bool {
        self.inner.contains(id)
    }

    /// `true` when every capability required by `required` is present locally.
    pub fn satisfies(&self, required: &CapabilitySet) -> bool {
        required.inner.is_subset(&self.inner)
    }

    pub fn intersection(&self, other: &CapabilitySet) -> CapabilitySet {
        CapabilitySet {
            inner: self.inner.intersection(&other.inner).cloned().collect(),
        }
    }

    pub fn union(&self, other: &CapabilitySet) -> CapabilitySet {
        CapabilitySet {
            inner: self.inner.union(&other.inner).cloned().collect(),
        }
    }

    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }

    pub fn len(&self) -> usize {
        self.inner.len()
    }

    pub fn iter(&self) -> impl Iterator<Item = &CapabilityId> {
        self.inner.iter()
    }
}

impl<T: Capability> FromIterator<T> for CapabilitySet {
    fn from_iter<I: IntoIterator<Item = T>>(iter: I) -> Self {
        let mut set = CapabilitySet::new();
        for capability in iter {
            set.insert(capability);
        }
        set
    }
}

/// The message a device emits when its capabilities change (or on registration).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CapabilityAdvert {
    pub device: DeviceId,
    pub capabilities: CapabilitySet,
    pub at: Timestamp,
}
